version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: always
    cpus: 0.5
    mem_limit: 500m
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - prometheus
      - node_exporter
  prometheus:
    image: prom/prometheus:latest
    cpus: 1.5
    mem_limit: 2g
    volumes:
      - ./prometheus:/etc/prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.external-url=http://localhost:8080/prometheus/

  node_exporter:
    image: prom/node-exporter:latest
    restart: always
    cpus: 0.1
    mem_limit: 50m
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
